@startuml
start
:Обновить статус задачи PROCESSING;
group анализ видео
    :поток = открыть(URL);
    :покадровые_характеристики = [];
    while (Не конец потока?)
        :читаем кадр из потока;
        :характеристика_кадра = Анализируем(кадр);
        :покадровые_характеристик.добавить(характеристика_кадра);
    endwhile
end group
group Прогноз качества
    :агрегированные_характеристики = Агрегируем(покадровые_характеристик);
    :данные = декартово_произведение(агрегированные_характеристики, набор_параметров_кодирования);
    :прогнозируемое_качество = модель.прогноз(данные);
end group
group выбор параметров
    if (есть качество выше 95) then (да)
        :оптимальные параметры = минимум_по_качеству(параметры[качество > 95]);
    else (нет)
        :оптимальные параметры = (crf 16);
    endif
end group
end
@enduml
